# Generated by Django 5.2.7 on 2025-10-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0002_subscriptionplan_transaction_usersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='icon',
        ),
    ]
