# Generated by Django 5.2.7 on 2025-11-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0003_remove_interest_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_active',
        ),
    ]
