# Generated by Django 5.2.7 on 2025-12-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0005_alter_usersubscription_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chat_backgrounds/')),
            ],
        ),
    ]
