# Generated by Django 5.2.7 on 2026-03-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0006_chatbackground'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_id',
            new_name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_status',
            field=models.CharField(blank=True, help_text='Raw status value from the payment gateway (e.g. captured, failed).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('one_time', 'One-time')], default='subscription', help_text='Whether this is a subscription purchase or a one-time payment.', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_part.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='created', max_length=50),
        ),
    ]
