# Generated by Django 5.2.7 on 2025-10-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0001_initial'),
        ('auth_api', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users', to='admin_part.interest'),
        ),
    ]
