# Generated by Django 5.2.7 on 2025-10-04 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_swipe_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='swipes_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
