# Generated by Django 5.2.7 on 2025-10-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_customuser_last_swipe_reset_customuser_swipes_today'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
