# Generated by Django 5.2.7 on 2025-10-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in cm', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('friendship', 'Friendship'), ('casual_dating', 'Casual Dating'), ('serious_relationship', 'Serious Relationship'), ('marriage', 'Marriage'), ('networking', 'Networking')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('in_a_relationship', 'In a Relationship')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(blank=True, choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('sikh', 'Sikh'), ('buddhist', 'Buddhist'), ('jain', 'Jain'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='would_like_to_meet',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('everyone', 'Everyone')], default='everyone', max_length=20),
        ),
    ]
