# Generated by Django 5.2.7 on 2025-11-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in cm', max_digits=6, null=True),
        ),
    ]
