# Generated by Django 5.2.7 on 2025-11-30 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_alter_userprofile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
