# Generated by Django 5.2.7 on 2025-12-01 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_customuser_qr_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='qr_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
