# Generated by Django 5.2.7 on 2025-12-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_part', '0006_chatbackground'),
        ('auth_api', '0013_alter_customuser_qr_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='admin_part.chatbackground'),
        ),
    ]
