# Generated by Django 5.2.7 on 2025-10-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='content_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
