# Generated by Django 5.2.7 on 2025-12-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_audiocall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiocall',
            name='is_active',
        ),
        migrations.AddField(
            model_name='audiocall',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiocall',
            name='status',
            field=models.CharField(choices=[('ringing', 'Ringing'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('ended', 'Ended')], default='ringing', max_length=20),
        ),
    ]
