# Generated by Django 5.2.7 on 2025-12-24 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_audiocall_is_active_audiocall_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiocall',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='audiocall',
            name='call_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10),
        ),
        migrations.AlterField(
            model_name='audiocall',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audiocall',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='audiocall',
            index=models.Index(fields=['status', 'call_type'], name='chat_audioc_status_cb108b_idx'),
        ),
        migrations.AddIndex(
            model_name='audiocall',
            index=models.Index(fields=['caller', 'receiver'], name='chat_audioc_caller__3090f9_idx'),
        ),
    ]
