# Generated by Django 5.2.7 on 2025-11-01 11:42

import feed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.JSONField(default=list, validators=[feed.models.validate_media_length]),
        ),
    ]
