# Generated by Django 5.2.7 on 2025-10-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe_feature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipe',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swipe',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swipe',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MatchRequest',
        ),
    ]
