# Generated by Django 5.2.7 on 2025-12-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('profile_view', 'Profile View'), ('new_match', 'New Match'), ('new_message', 'New Message'), ('story_view', 'Story View'), ('like', 'Post Like'), ('comment', 'Post Comment'), ('system', 'System Notification'), ('incoming_call', 'Incoming Call'), ('missed_call', 'Missed Call'), ('call_ended', 'Call Ended')], max_length=50),
        ),
    ]
